USE [TPCC100];
GO

SET NOCOUNT ON;

WHILE (1=1)
BEGIN
	INSERT INTO addresses SELECT REPLICATE('a',7000)
	INSERT INTO addresses SELECT REPLICATE('a',7000)
	INSERT INTO addresses SELECT REPLICATE('a',7000)
	INSERT INTO addresses SELECT REPLICATE('a',7000)
	INSERT INTO addresses SELECT REPLICATE('a',7000)
    WAITFOR DELAY '00:00:01'
END;
GO