USE [TPCC100];
GO

SET NOCOUNT ON;

WHILE (1=1)
BEGIN
	INSERT INTO T1 SELECT REPLICATE('a',84)
	INSERT INTO T1 SELECT REPLICATE('a',84)
	INSERT INTO T1 SELECT REPLICATE('a',84)
	INSERT INTO T1 SELECT REPLICATE('a',84)
	INSERT INTO T1 SELECT REPLICATE('a',84)
    WAITFOR DELAY '00:00:01'
END;
GO